server.port: ${SERVER_PORT:9088}
application-properties:
  p6spy:
    max-length: 10000
spring:
  application.name: spring-base-event
  cloud:
    function:
      definition: newPost;newSubscriber;newComment;newPostFollowing
    stream:
      bindings:
        newPost-in-0:
          destination: ${application-properties.message-topic.new-post.topic-name}
          group: ${spring.application.name}
        newSubscriber-in-0:
          destination: ${application-properties.message-topic.new-subscriber.topic-name}
          group: ${spring.application.name}
        newComment-in-0:
          destination: ${application-properties.message-topic.new-comment.topic-name}
          group: ${spring.application.name}
        newPostFollowing-in-0:
          destination: ${application-properties.message-topic.new-post-following.topic-name}
          group: ${spring.application.name}
      default-binder: rabbit
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_BD:spring-base-event}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:123456}
  liquibase.enabled: ${LIQUIBASE_ENABLED:true}
  output.ansi.enabled: ALWAYS
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:rabbitmq}
    password: ${RABBITMQ_PASSWORD:123456}
  threads.virtual.enabled: ${VIRTUAL_THREADS_ENABLED:true}
decorator.datasource.p6spy:
  custom-appender-class: com.vulinh.utils.MyP6SpyLogging
  logging: CUSTOM
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,env
